language: python
matrix:
  include:
    - python: 3.6
      dist: xenial
      services: xvfb
    - python: 3.7
      dist: xenial
      services: xvfb
    - python: 3.8
      dist: xenial
      services: xvfb

cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - pip install coveralls
  - pip install future
  - pip install pysatCDF >/dev/null

# command to install dependencies
install:
  - source activate test-environment
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0

# command to run tests
script:
 - nosetests -vs --with-coverage --cover-package=pysat

after_success:
 - coveralls
