language: python
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 2.7
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip
cache:
   directories:
      - ../pyglow_cache

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

# Setup anaconda
before_install:
  #- apt-get update
  - pip install coveralls
  - pip install future
  - pip install matplotlib
  - pip install netCDF4
  - pip install beautifulsoup4
  - pip install lxml
  - pip install pysatCDF >/dev/null
  # install pyglow, space science models
  - cd ..
  - echo 'cloning pyglow'
  - git clone https://github.com/timduly4/pyglow.git >/dev/null
  - echo 'installing pyglow'
  - cd ./pyglow
  - make -C src/pyglow/models source >/dev/null
  - python setup.py install >/dev/null
  - cd ..

# command to install dependencies
install:
  - source activate test-environment
  # set up data directory
  - mkdir /home/travis/build/rstoneback/pysatData
  # install pysat
  - cd /home/travis/build/rstoneback/pysat
  - python setup.py install

# Set up a display for plot tests
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3  # give xvfb some time to start

# command to run tests
script:
 - nosetests -vs --with-coverage --cover-package=pysat

after_success:
 - coveralls
