language: python
matrix:
  include:
    - python: 2.7.14
      services: xvfb
    - python: 3.7
      dist: xenial
      services: xvfb

cache: pip
cache:
   directories:
      - ../pyglow_cache

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

# Setup anaconda
before_install:
  #- apt-get update
  - pip install coveralls
  - pip install future
  - pip install pandas
  - pip install xarray
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install pysatCDF >/dev/null
  # install pyglow, space science models
  - cd ..
  - echo 'cloning pyglow'
  - git clone https://github.com/timduly4/pyglow.git >/dev/null
  - echo 'installing pyglow'
  - cd ./pyglow
  - make -C src/pyglow/models source >/dev/null
  - python setup.py install >/dev/null
  - cd ..

# command to install dependencies
install:
  - source activate test-environment
  # set up data directory
  - mkdir /home/travis/build/pysat/pysatData
  # install pysat
  - cd /home/travis/build/pysat/pysat
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0
  - if [[ $TRAVIS_PYTHON_VERSION < "3.7" ]]; then
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

# command to run tests
script:
 - nosetests -vs --with-coverage --cover-package=pysat

after_success:
 - coveralls
